src/Entity/Jeu.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\JeuRepository")
 */
class Jeu
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $joueurs_min;

    /**
     * @ORM\Column(type="integer")
     */
    private $joueurs_max;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $annee;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Location", mappedBy="jeu")
     */
    private $locations;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Editeur", inversedBy="jeux")
     */
    private $editeur;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Genre", inversedBy="jeux")
     */
    private $genre;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Auteur", inversedBy="jeux")
     */
    private $auteur;

    /**
     * @ORM\Column(type="integer")
     */
    private $copies;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
        $this->genre = new ArrayCollection();
        $this->auteur = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getJoueursMin(): ?int
    {
        return $this->joueurs_min;
    }

    public function setJoueursMin(int $joueurs_min): self
    {
        $this->joueurs_min = $joueurs_min;

        return $this;
    }

    public function getJoueursMax(): ?int
    {
        return $this->joueurs_max;
    }

    public function setJoueursMax(int $joueurs_max): self
    {
        $this->joueurs_max = $joueurs_max;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getAnnee(): ?int
    {
        return $this->annee;
    }

    public function setAnnee(int $annee): self
    {
        $this->annee = $annee;

        return $this;
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
            $location->setJeu($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getJeu() === $this) {
                $location->setJeu(null);
            }
        }

        return $this;
    }

    public function getEditeur(): ?editeur
    {
        return $this->editeur;
    }

    public function setEditeur(?editeur $editeur): self
    {
        $this->editeur = $editeur;

        return $this;
    }

    /**
     * @return Collection|genre[]
     */
    public function getGenre(): Collection
    {
        return $this->genre;
    }

    public function addGenre(genre $genre): self
    {
        if (!$this->genre->contains($genre)) {
            $this->genre[] = $genre;
        }

        return $this;
    }

    public function removeGenre(genre $genre): self
    {
        if ($this->genre->contains($genre)) {
            $this->genre->removeElement($genre);
        }

        return $this;
    }

    /**
     * @return Collection|auteur[]
     */
    public function getAuteur(): Collection
    {
        return $this->auteur;
    }

    public function addAuteur(auteur $auteur): self
    {
        if (!$this->auteur->contains($auteur)) {
            $this->auteur[] = $auteur;
        }

        return $this;
    }

    public function removeAuteur(auteur $auteur): self
    {
        if ($this->auteur->contains($auteur)) {
            $this->auteur->removeElement($auteur);
        }

        return $this;
    }

    public function isLocated(): bool
    {
        $locationAll = $this->locations;

        $isLocated = false;
        $locationSize = count($locationAll);

        if ($locationSize > 0) {
            for ($i = 0; $i < $locationSize; $i++) {
                if ($locationAll[$i]->getOk() == false) {
                    $isLocated = true;
                }
            }
        }

        return $isLocated;
    }

    public function getCopies(): ?int
    {
        return $this->copies;
    }

    public function setCopies(int $copies): self
    {
        $this->copies = $copies;

        return $this;
    }
}

src/Controller/JeuController.php
<?php

namespace App\Controller;

use App\Entity\Jeu;
use App\Entity\Location;
use App\Form\CreateJeuType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class JeuController extends AbstractController
{
    /**
     * @Route("/jeu", name="jeu")
     */
    public function index()
    {
        $jeux = $this->getDoctrine()->getRepository(Jeu::Class)->findBy([], array('titre' => 'ASC'));

        return $this->render('jeu/index.html.twig', [
            'jeux' => $jeux,
        ]);
    }

    /**
     * @Route("/jeu/add", name="jeu_add")
     */
    public function add_jeu(Request $request)
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $entityManager = $this->getDoctrine()->getManager();
        
        $jeu = new Jeu();

        $form = $this->createForm(CreateJeuType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $jeu = $form->getData();

            $entityManager->persist($jeu);

            $entityManager->flush();

            return $this->redirectToRoute('confirmation', ['id' => $jeu->getId(), "entity" => "jeu"]);
        }

        return $this->render("jeu/new.html.twig", [
            "form" => $form->createView(),
        ]);
    }

    /**
     * @Route("jeu/{id}", name="jeu_show")
     */
    public function show_jeu(int $id)
    {
        $jeu = $this->getDoctrine()->getRepository(Jeu::class)->find($id);
        if (!$jeu)
        {
            throw $this->createNotFoundError(
                "Pas de jeu avec l'id ".$id
            );
        }

        $locations = $this->getDoctrine()->getRepository(Location::class)->findBy(array('jeu' => $id));
        
        return $this->render("jeu/details.html.twig", [
            "jeu" => $jeu,
            "editeur" => $jeu->getEditeur(),
        ]);
    }

    /**
     * @Route("jeu/{id}/edit", name="jeu_edit")
     */
    public function update_jeu(int $id, Request $request)
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $entityManager = $this->getDoctrine()->getManager();
        $jeu = $entityManager->getRepository(Jeu::class)->find($id);

        if(!$jeu)
        {
            throw $this->createNotFoundException(
                "Pas de jeu correspondant à l'id ".$id
            );
        }

        $form = $this->createForm(CreateJeuType::class, $jeu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $jeu = $form->getData();
            $entityManager->persist($jeu);
            $entityManager->flush();

            return $this->redirectToRoute("jeu_show", ['id' => $id]);
        }

        return $this->render("jeu/update.html.twig", [
            "jeu" => $jeu,
            "form" => $form->createView(),
        ]);

    }

    /**
     * @Route("jeu/{id}/delete", name="jeu_delete")
     */
    public function delete_jeu($id)
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $em = $this->getDoctrine()->getManager();
        $jeu = $em->getRepository(Jeu::class)->find($id);

        $em->remove($jeu);
        $em->flush();

        return $this->render("confirmation_delete.html.twig", [
            "id" => $id,
            "entity" => "jeu",
        ]);
    }
}

templates/jeu/details.html.twig
{% extends "jeu/layout.html.twig" %}
{% block javascripts %}
	<script>
		function confirm_delete_jeu() {
if (confirm("Supprimer le jeu ?\nAttention, cette action est définitive !")) {
window.location.replace("{{ jeu.id }}/delete");
}
}
	</script>
{% endblock %}
{% block page_title %}
	<h2>{{ jeu.titre|capitalize }}</h2>
{% endblock %}
{% block content %}
	<div class='sidebyside'>
		<article>
			<p>
				De
				{{ jeu.joueursMin }}
				à
				{{ jeu.joueursMax }}
				joueurs.
			</p>
			<p>Durée :
				{{ jeu.duree }}
				min.
			</p>
			{% if jeu.annee %}
				<p>Sortie en
					{{ jeu.annee }}</p>
			{% endif %}
			{% if editeur %}
				<p>Édité par
					{{editeur.name}}
				</p>
			{% endif %}
			{% if jeu.description %}
				<p>
					Description :<br/>
					{{ jeu.description }}</p>
			{% endif %}
			{% if jeu.isLocated == FALSE %}
				<p class='ok'>Jeu disponible</p>
			{% else %}
				<p class='ko'>Jeu indisponible actuellement</p>
			{% endif %}

			<!-- TODO: ajouter auteur -->
			<!-- TODO: ajouter genre -->
		</article>
		{% if is_granted("ROLE_KEJ") %}
			<aside>
				<button onclick="document.location = '{{ jeu.id }}/edit'">Modifier</button>
				<button onclick="confirm_delete_jeu()">Supprimer</button>
				{% if jeu.isLocated == FALSE %}
					<button onclick="document.location = '{{ path("location_add", {jeu: jeu.id}) }}'">Nouvelle location</button>
				{% endif %}
			</aside>
		{% endif %}
	</div>
{% endblock %}

templates/jeu/index.html.twig
{% extends 'jeu/layout.html.twig' %}

{% block title %}Liste des jeux{% endblock %}

{% block page_title %}<h2>Liste des jeux</h2>{% endblock %}

{% block content %}
<ul>
    {% for jeu in jeux %}
        <a href="jeu/{{ jeu.id }}"><li>{{ jeu.titre }}</li></a>
    {% endfor %}
</ul>
{% if is_granted("ROLE_KEJ") %}<button class="bottom_button" onclick="document.location = 'jeu/add'">Ajouter un nouveau jeu</button>{% endif %}
{% endblock %}

templates/jeu/layout.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% block page_title %}<h2>Jeu</h2>{% endblock %}
    {% block content %}{% endblock %}
{% endblock %}

templates/jeu/new.html.twig
{% extends 'jeu/layout.html.twig' %}

{% block title %}Ajouter un jeu{% endblock %}

{% block page_title %}<h2>Ajouter un jeu</h2>{% endblock %}

{% block content %}
    {{ form(form) }}
{% endblock %}

templates/jeu/update.html.twig
{% extends 'jeu/layout.html.twig' %}

{% block title %}Modifier un jeu{% endblock %}

{% block page_title %}<h2>Modifier la location</h2>{% endblock %}

{% block content %}
    {{ form(form) }}
{% endblock %}