src/Entity/Location.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LocationRepository")
 */
class Location
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Personne", inversedBy="locations")
     * @ORM\JoinColumn(nullable=true)
     */
    private $personne;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Jeu", inversedBy="locations")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     * @ORM\OrderBy({"titre" = "ASC"})
     */
    private $jeu;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="boolean")
     */
    private $paye;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="boolean")
     */
    private $ok;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPersonne(): ?personne
    {
        return $this->personne;
    }

    public function setPersonne(?personne $personne): self
    {
        $this->personne = $personne;

        return $this;
    }

    public function getJeu(): ?jeu
    {
        return $this->jeu;
    }

    public function setJeu(?jeu $jeu): self
    {
        $this->jeu = $jeu;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getPaye(): ?bool
    {
        return $this->paye;
    }

    public function setPaye(bool $paye): self
    {
        $this->paye = $paye;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(?string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getOk(): ?bool
    {
        return $this->ok;
    }

    public function setOk(bool $ok): self
    {
        $this->ok = $ok;

        return $this;
    }

    public function enRetard(): bool
    {
        $today = new \DateTime();
        $today->setTime(0, 0);

        if ($this->date_fin > $today) {
            return false;
        } else {
            return true;
        }
    }
}

src/Controller/LocationController.php
<?php

namespace App\Controller;

use App\Entity\Jeu;
use App\Entity\Location;
use App\Form\CreateLocationType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LocationController extends AbstractController
{
    /**
     * @Route("/location", name="location")
     */
    public function index(): Response
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $locations = $this->getDoctrine()->getRepository(Location::class)->findBy(array('ok' => false));

        return $this->render('location/index.html.twig', [
            'locations' => $locations,
        ]);
    }

    /**
     * @Route("/location/all", name="location_all")
     */
    public function index_all(): Response
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $locations = $this->getDoctrine()->getRepository(Location::class)->findAll();

        return $this->render('location/index.html.twig', [
            'locations' => $locations,
        ]);
    }

    /**
     * @Route("/location/jeux", name="location_jeux")
     */
    public function index_jeux(): Response
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $locations = $this->getDoctrine()->getRepository(Location::class)->findLocatedGamesByGamesTitle();

        return $this->render("location/index.html.twig", [
            "locations" => $locations,
        ]);
    }

    /**
     * @Route("location/retard", name="location_retard")
     */
    public function index_retard(): Response
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $locations = $this->getDoctrine()->getRepository(Location::class)->findBy(array('ok' => false));

        $locationsEnRetard = array_filter($locations, function ($v) {
            return $v->enRetard();
        });

        return $this->render("location/index.html.twig", [
            "locations" => $locationsEnRetard,
        ]);
    }

    /**
     * @Route("/location/add/{jeuId}", name="location_add")
     */
    public function add_location(Request $request, $jeuId = null)
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");
        $jeu = null;

        if ($jeuId) {
            $jeu = $this->getDoctrine()->getRepository(Jeu::class)->find($jeuId);
        } elseif ($request->query->get("jeu")) {
            $jeuId = $request->query->get("jeu");
            $jeu = $this->getDoctrine()->getRepository(Jeu::class)->find($jeuId);
        }

        $entityManager = $this->getDoctrine()->getManager();

        $location = new Location();

        $form = $this->createForm(CreateLocationType::class, $location, array(
            'jeu_default' => $jeu,
        ));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $location = $form->getData();
            $location->setOk(false);

            $entityManager->persist($location);
            $entityManager->flush();

            return $this->redirectToRoute('location');
        }

        return $this->render("location/new.html.twig", [
            "form" => $form->createView(),
        ]);
    }

    /**
     * @Route("location/{id}/", name="location_show")
     */
    public function show_location(int $id)
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $location = $this->getDoctrine()->getRepository(Location::class)->find($id);

        return $this->render("location/details.html.twig", [
            "location" => $location,
        ]);
    }

    /**
     * @Route("location/{id}/paiement", name="location_paiement")
     */
    public function location_is_payed(int $id)
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $entityManager = $this->getDoctrine()->getManager();

        $location = $this->getDoctrine()->getRepository(Location::class)->find($id);

        $location->setPaye(true);

        $entityManager->persist($location);

        $entityManager->flush();

        return $this->redirectToRoute('location_show', ["id" => $id]);
    }

    /**
     * @Route("location/{id}/retour", name="location_retour")
     */
    public function retour_location(int $id)
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $em = $this->getDoctrine()->getManager();

        $location = $this->getDoctrine()->getRepository(Location::class)->find($id);

        $location->setOk(true);

        $em->persist($location);
        $em->flush();

        return $this->redirectToRoute('location_show', ["id" => $id]);
    }

    /**
     * @Route("location/{id}/edit" , name="location_edit")
     */
    public function update_location(int $id, Request $request)
    {
        $this->denyAccessUnlessGranted("ROLE_KEJ");

        $em = $this->getDoctrine()->getManager();

        $location = $em->getRepository(Location::class)->find($id);

        if (!$location) {
            throw $this->createNotFoundException(
                "Pas de location correspondant à l'id."
            );
        }

        $form = $this->createForm(CreateLocationType::class, $location);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $location = $form->getData();
            $em->persist($location);
            $em->flush();

            return $this->redirectToRoute("location");
        }

        return $this->render("jeu/update.html.twig", [
            "location" => $location,
            "form" => $form->createView(),
        ]);
    }
}

templates/location/details.html.twig
{% extends 'location/layout.html.twig' %}
{% block page_title %}
	<h2>Location</h2>
{% endblock %}
{% block content %}
	<div class="sidebyside">
		<article>
			<p>
				<strong>Jeu :
				</strong>
				{{ location.jeu.titre }}
			</p>
			<p>
				<strong>Loué par :</strong>
				{{ location.nom }}</p>
			{% if location.mail %}
				- Mail :
				{{ location.mail }}
			{% endif %}
			{% if location.phone %}
				- Phone :
				{{ location.phone }}
			{% endif %}
			<p>
				Du
				{{ location.dateDebut.format('d M y') }}
				au
				{{ location.dateFin.format('d M y') }}
			</p>
			<p>
				<strong>Payé :
				</strong>
				{% if location.paye == 1 %}
					Oui
				{% else %}
					Non
				{% endif %}
			</p>
			<p>Rendu :
				{% if location.ok == 1 %}
					Oui
				{% else %}
					Non
				{% endif %}
			</p>
		</article>
		<aside>
			<button onclick="document.location = '{{ path("location_paiement", {"id": location.id}) }}'">Paiement reçu</button>
			<button onclick="document.location = '{{path("location_retour", {"id": location.id}) }}'">Jeu rendu</button>
			<button onclick="document.location = '{{ path("location_edit", { "id":location.id}) }}'">Modifier location</button>
		</aside>
	</div>
{% endblock %}

templates/location/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Locations en cours
{% endblock %}

{% block body %}
	<h2>Locations en cours</h2>
	<table id="current_locations">
		<thead>
			<tr>
				<th scope="col">ID</th>
				<th scope="col">Jeu</th>
				<th scope="col">Personne</th>
				<th scope="col">Date de prêt</th>
				<th scope="col">Date de retour</th>
				<th scope="col">Payé</th>
				<th scope="col"></th>
			</tr>
		</thead>
		{% for location in locations %}
			<tbody>
				<tr>
					<td>{{ location.id }}</td>
					<td>{{ location.jeu.titre }}</td>
					<td>{{ location.nom }}</td>
					<td>{{ location.dateDebut.format("d-m-y") }}</td>
					{% if location.enRetard and location.ok == FALSE %}
						<td class='ko'>{{ location.dateFin.format("d-m-y") }}</td>
					{% else %}
						<td>{{ location.dateFin.format("d-m-y") }}</td>
					{% endif %}
					{% if location.paye == 1 %}
						<td>Oui</td>
					{% else %}
						<td>Non</td>
					{% endif %}
					<td>
						<button onclick="document.location = '{{ path('location_show', {'id' : location.id}) }}'">Détails</button>
					</td>
				</tr>
			</tbody>
		{% endfor %}
	</table>
	<button class="bottom_button" onclick="document.location = '{{ path('location_jeux') }}'">Classer par jeu</button>
	<button class="bottom_button" onclick="document.location = '{{ path('location') }}'">Classer par date</button><br/>
	<button class="bottom_button" onclick="document.location = '{{ path('location_add') }}'">Nouvelle location</button>
{% endblock %}

templates/location/layout.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% block page_title %}<h2>Location</h2>{% endblock %}
    {% block content %}{% endblock %}
{% endblock %}

templates/location/new.html.twig
{% extends 'location/layout.html.twig' %}

{% block title %}Nouvelle location{% endblock %}

{% block page_title %}<h2>Nouvelle location</h2>{% endblock %}

{% block content %}
    {{ form(form) }}
{% endblock %}

templates/location/update.html.twig
{% extends 'location/layout.html.twig' %}

{% block title %}Modifier une location{% endblock %}

{% block page_title %}<h2>Modifier la location</h2>{% endblock %}

{% block content %}
    {{ form(form) }}
{% endblock %}